#!/bin/sh
set -e
set -x
please() {
  gittemp=`mktemp -d`
  git clone --depth=1 https://github.com/jhazelwo/sh.git $gittemp
  install -v -m 0700 -d bin
  install -v -m 0700 $gittemp/bin/* bin/
  install -v -m 0700 -d lib
  install -v -m 0700 $gittemp/lib/* lib/
  rm -rf $gittemp
  install -v -m 0700 /dev/null bin/netshow
}

thanks() {
  curl -s https://raw.githubusercontent.com/jhazelwo/python-netshow/master/netshow/netshow.py > bin/netshow
}

please && thanks
